[server]
baseUrlPath = ""

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
  
[theme]
primaryColor = "#55b82e"
backgroundColor = "white"
secondaryBackgroundColor = "#e2f6ff"
textColor = "#31333F"
font = "sans serif"