[server]
baseUrlPath = ""

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "white"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"