username="Admin"
password="Hallo1234"
openai-key="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"
